import React, { useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import { Activity, Check, ChevronDown, Download, Grid2X2, LayoutDashboard, Plus, Search, ShieldCheck, SlidersHorizontal, Sparkles, Table2, Type, Users } from "lucide-react";
import { Brand } from "../../components/Brand";
import { ActionButton, Breadcrumb, Card, StatCard, StatusBadge } from "../../components/Operational";
import "../../styles/global.css";
import "./components.css";

type Tab = "Foundations" | "Components" | "Patterns";
const tabs: Tab[] = ["Foundations", "Components", "Patterns"];

function Foundations() {
  return <section className="cc-section"><div className="cc-section-heading"><div><span className="cc-kicker">Foundations</span><h2>Uma base consistente para todas as telas</h2><p>Tokens semânticos orientam cor, tipografia, espaçamento, radius e elevação.</p></div></div><div className="cc-foundation-grid"><Card className="cc-foundation-card"><div className="cc-foundation-title"><span className="cc-foundation-icon"><Sparkles /></span><div><h3>Cores</h3><p>Marca, conteúdo, superfícies e estados.</p></div></div><div className="cc-swatches"><span style={{ background: "hsl(349 78% 58%)" }}><b>brand</b><small>#EF3658</small></span><span style={{ background: "hsl(222 32% 12%)" }}><b>ink</b><small>#101828</small></span><span style={{ background: "hsl(220 22% 98%)" }}><b>subtle</b><small>#F8F9FB</small></span><span style={{ background: "hsl(160 70% 42%)" }}><b>success</b><small>#129B72</small></span></div></Card><Card className="cc-foundation-card"><div className="cc-foundation-title"><span className="cc-foundation-icon"><Type /></span><div><h3>Tipografia</h3><p>Inter local, com escala para operação.</p></div></div><div className="cc-type-samples"><span className="cc-type-display">Aa</span><div><strong>Inter 600</strong><small>Títulos e números</small></div><div><strong className="cc-type-body">Inter 400</strong><small>Texto auxiliar e descrições</small></div></div></Card><Card className="cc-foundation-card"><div className="cc-foundation-title"><span className="cc-foundation-icon"><Grid2X2 /></span><div><h3>Radius e spacing</h3><p>Geometria previsível e compacta.</p></div></div><div className="cc-radius-samples"><span data-radius="sm">6</span><span data-radius="md">8</span><span data-radius="lg">12</span><span data-radius="xl">16</span></div><div className="cc-spacing-scale"><i /><i /><i /><i /><i /></div><small className="cc-foundation-note">Grade base de 4px · controles 32–40px</small></Card></div></section>;
}

const componentRows = [
  { name: "Card", detail: "Container de conteúdo", use: "Dashboards e detalhes", status: "Pronto", tone: "success" as const },
  { name: "StatCard", detail: "KPI e big number", use: "Resumo de operação", status: "Pronto", tone: "success" as const },
  { name: "ActionButton", detail: "Ações com intenção", use: "Headers e toolbars", status: "Pronto", tone: "success" as const },
  { name: "Breadcrumb", detail: "Hierarquia de página", use: "Headers compactos", status: "Pronto", tone: "success" as const },
  { name: "DataTable", detail: "Dados operacionais", use: "Listas, filtros e edição", status: "Em evolução", tone: "warning" as const },
  { name: "AppShell", detail: "Estrutura de aplicação", use: "Sidebar, header e conteúdo", status: "Pronto", tone: "success" as const },
  { name: "PageHeader", detail: "Cabeçalho compacto", use: "Títulos, contexto e ações", status: "Pronto", tone: "success" as const },
  { name: "Toolbar", detail: "Ações contextuais", use: "Busca, filtros e ordenação", status: "Pronto", tone: "success" as const },
  { name: "StatusBadge", detail: "Estado semântico", use: "Status de operação", status: "Pronto", tone: "success" as const },
  { name: "Pagination", detail: "Navegação de páginas", use: "Tabelas e resultados", status: "Pronto", tone: "success" as const },
  { name: "SidePanel", detail: "Conteúdo contextual", use: "Detalhes e edição", status: "Pronto", tone: "success" as const },
  { name: "DatePicker", detail: "Datas e intervalos", use: "Filtros e formulários", status: "Em evolução", tone: "warning" as const },
  { name: "Calendar", detail: "Visão temporal", use: "Cronogramas e agenda", status: "Planejado", tone: "neutral" as const },
  { name: "DropdownMenu", detail: "Ações secundárias", use: "Menus de contexto", status: "Planejado", tone: "neutral" as const },
  { name: "Dialog", detail: "Confirmações e foco", use: "Fluxos críticos", status: "Planejado", tone: "neutral" as const },
  { name: "FilterBar", detail: "Filtros compactos", use: "Listas densas", status: "Em evolução", tone: "warning" as const },
  { name: "EmptyState", detail: "Estado sem dados", use: "Busca e onboarding", status: "Planejado", tone: "neutral" as const },
  { name: "ChartCard", detail: "Visualização de dados", use: "Dashboards", status: "Em evolução", tone: "warning" as const },
  { name: "Toast", detail: "Feedback não bloqueante", use: "Confirmações e alertas", status: "Planejado", tone: "neutral" as const },
];

function Components({ search, onInspect }: { search: string; onInspect: (name: string) => void }) {
  const rows = componentRows.filter((row) => `${row.name} ${row.detail} ${row.use}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  return <><section className="cc-section"><div className="cc-section-heading"><div><span className="cc-kicker">Components</span><h2>Primitivos para compor produtos</h2><p>Componentes com variantes, estados e regras de uso explícitas.</p></div></div><div className="cc-grid cc-grid-stats"><StatCard label="Participantes confirmados" value="582" detail="de 750 previstos" trend="+12,4%" trendTone="positive" icon={<Activity />} variant="featured" /><StatCard label="RSVP pendente" value="147" detail="19,6% da base" icon={<Users />} /><StatCard label="Prontos para emissão" value="0" detail="aguardando cadastro" icon={<ShieldCheck />} /></div></section><section className="cc-section"><div className="cc-section-heading"><div><h2>Botões e estados</h2><p>Uma ação primária por região; o restante apoia a tarefa.</p></div></div><Card className="cc-showcase-row"><div className="cc-button-row"><ActionButton icon={<Plus />}>Novo participante</ActionButton><ActionButton variant="secondary" icon={<Download />}>Exportar</ActionButton><ActionButton variant="ghost">Cancelar</ActionButton><ActionButton size="sm" variant="secondary" icon={<ChevronDown />}>Mais opções</ActionButton></div><div className="cc-status-row"><StatusBadge tone="success">Confirmado</StatusBadge><StatusBadge tone="warning">Pendente RSVP</StatusBadge><StatusBadge tone="danger">Cadastro incompleto</StatusBadge><StatusBadge tone="neutral">Rascunho</StatusBadge></div></Card></section><section className="cc-section"><div className="cc-section-heading"><div><h2>Inventário</h2><p>{rows.length} de {componentRows.length} componentes listados.</p></div></div><Card className="cc-table-card"><table><thead><tr><th>Componente</th><th>Uso</th><th>Estado</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.name}><td><strong>{row.name}</strong><small>{row.detail}</small></td><td>{row.use}</td><td><StatusBadge tone={row.tone}>{row.tone === "success" ? <><Check /> </> : null}{row.status}</StatusBadge></td><td><button className="cc-row-action" type="button" onClick={() => onInspect(row.name)}>Inspecionar</button></td></tr>)}</tbody></table>{rows.length === 0 ? <div className="cc-empty">Nenhum componente encontrado.</div> : null}</Card></section></>;
}

function Patterns() {
  const go = (url: string) => { const target = new URL(url, window.location.origin); target.searchParams.set("from", "catalog"); window.location.href = `${target.pathname}${target.search}${target.hash}`; };
  return <><section className="cc-section"><div className="cc-section-heading"><div><span className="cc-kicker">Patterns</span><h2>Composições orientadas ao trabalho</h2><p>Modelos para resolver tarefas completas, não apenas telas bonitas.</p></div></div><div className="cc-pattern-grid"><Card className="cc-pattern-card"><div className="cc-pattern-preview"><LayoutDashboard /><div><strong>Dashboard operacional</strong><small>KPIs · gráfico · prioridades</small></div></div><div className="cc-pattern-meta"><span>Home de produto</span><button type="button" onClick={() => go("/prototypes/navigation/#evento")}>Ver referência</button></div></Card><Card className="cc-pattern-card"><div className="cc-pattern-preview"><Table2 /><div><strong>Lista com filtros</strong><small>Busca · colunas · resumo</small></div></div><div className="cc-pattern-meta"><span>Data-heavy</span><button type="button" onClick={() => go("/prototypes/data-table/?v=1")}>Ver referência</button></div></Card><Card className="cc-pattern-card"><div className="cc-pattern-preview"><SlidersHorizontal /><div><strong>Shell de navegação</strong><small>Sidebar · breadcrumb · header</small></div></div><div className="cc-pattern-meta"><span>App shell</span><button type="button" onClick={() => go("/prototypes/navigation/#evento")}>Ver referência</button></div></Card></div></section><section className="cc-section cc-pattern-rules"><h2>Regras de composição</h2><div><p><strong>01</strong> Comece pela tarefa principal e deixe o contexto apoiar a decisão.</p><p><strong>02</strong> Use cards para agrupar significado, não para decorar a página.</p><p><strong>03</strong> Prefira uma ação primária clara e estados que expliquem o próximo passo.</p></div></section></>;
}

function ComponentCatalog() {
  const [notice, setNotice] = useState<string | null>(null);
  const [selectedTab, setSelectedTab] = useState<Tab>(() => window.location.hash === "#components" ? "Components" : window.location.hash === "#patterns" ? "Patterns" : "Foundations");
  const [search, setSearch] = useState("");
  const [inspected, setInspected] = useState<string | null>(null);
  const content = useMemo(() => selectedTab === "Foundations" ? <Foundations /> : selectedTab === "Components" ? <Components search={search} onInspect={setInspected} /> : <Patterns />, [search, selectedTab]);
  function selectTab(tab: Tab) { setSelectedTab(tab); window.history.replaceState(null, "", `#${tab.toLocaleLowerCase()}`); }
  return <main className="cc-shell"><header className="cc-header"><a href="#inicio" aria-label="Ir para o início"><Brand className="cc-logo" /></a><div className="cc-header-copy"><Breadcrumb items={[{ label: "Eventesse" }, { label: "Design System", current: true }]} /><h1>Catálogo de componentes</h1><p>Referência visual e funcional para produtos operacionais.</p></div><ActionButton variant="secondary" size="sm" icon={<Download />} onClick={() => setNotice("A referência está pronta para exportação no produto consumidor.")}>Exportar referência</ActionButton></header><nav className="cc-tabs" aria-label="Seções do catálogo">{tabs.map((tab) => <button key={tab} type="button" role="tab" aria-selected={selectedTab === tab} aria-current={selectedTab === tab ? "page" : undefined} onClick={() => selectTab(tab)}>{tab}</button>)}</nav>{selectedTab === "Components" ? <div className="cc-global-search"><label className="cc-search"><Search aria-hidden="true" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar componente..." aria-label="Buscar componente" /></label></div> : null}<div className="cc-content">{content}</div>{notice ? <div className="cc-toast" role="status">{notice}</div> : null}{inspected ? <div className="cc-inspector-backdrop" role="presentation" onClick={() => setInspected(null)}><section className="cc-inspector" role="dialog" aria-modal="true" aria-labelledby="inspector-title" onClick={(event) => event.stopPropagation()}><header><div><span className="cc-kicker">Inspeção</span><h2 id="inspector-title">{inspected}</h2></div><button type="button" aria-label="Fechar inspeção" onClick={() => setInspected(null)}>×</button></header><p>Componente disponível para composição. Consulte variantes, estados e tokens antes de levar para um produto.</p><pre>{`import { ${inspected} } from "@eventesse/design-system";\n\n<${inspected} />`}</pre><ActionButton onClick={() => setInspected(null)}>Fechar</ActionButton></section></div> : null}</main>;
}

ReactDOM.createRoot(document.getElementById("prototype-root")!).render(<React.StrictMode><ComponentCatalog /></React.StrictMode>);
